#!/bin/sh
#
# Script to monitor ACPI battery capacity values.
#
# Configuration (ex. Thinkpad R400):
#
# [battery_capacity]
#   env.design 56160
#   env.ulimit 60000
#   env.llimit 0
#   env.warning 28050
#   env.critical 11220
#
# Parameters understood:
#
#   config   (required)
#   autoconf (optional - used by munin-config)
#
# $Log$
# Revision 0.3  2012/11/24 13:00:00  andersevenrud@gmail.com
#               Now using munin-node as config
# Revision 0.2  2012/11/23 21:20:00  andersevenrud@gmail.com
#               Configuration added
# Revision 0.1  2012/11/22 15:20:00  andersevenrud@gmail.com
#               Initial version
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=manual
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

CAPACITY_DESIGN="$design" # "56160"
CAPACITY_ULIMIT="$ulimit" # "60000"
CAPACITY_LLIMIT="$llimit" # "0"
CAPACITY_WARNING="$warning" # "28050"
CAPACITY_CRITICAL="$critical" # "11220"

if [ "$1" = "autoconf" ]; then
  if [ -r /proc/acpi/battery/BAT* ]; then
    echo yes
    exit 0
  else
    echo no
    exit 0
  fi
fi

if [ "$1" = "config" ]; then
  if [[ "${CAPACITY_ULIMIT}" == "" && "${CAPACITY_LLIMIT}" == "" && "${CAPACITY_WARNING}" == "" && "${CAPACITY_CRITICAL}" == "" ]] ; then
    echo "No configuration given" >&2
    exit -1
  fi

  echo 'graph_title Battery Capacity'
  echo "graph_args -u $CAPACITY_ULIMIT -l $CAPACITY_LLIMIT"
  echo 'graph_vlabel mWh'
  echo 'graph_category ACPI'
  echo 'graph_info This graph shows remaining battery capacity.'

  for TYPE in `ls /proc/acpi/battery`; do
    VALUE=`cat /proc/acpi/battery/$TYPE/state | grep remaining | awk '{print $3}'`

    echo  "capacity_$TYPE.warning $CAPACITY_WARNING:"
    echo  "capacity_$TYPE.critical $CAPACITY_CRITICAL:"
    echo  "capacity_$TYPE.label $TYPE"
    echo  "capacity_$TYPE.value $VALUE"
  done

  exit 0
fi
