#!/bin/sh
#
# Script to monitor ACPI battery voltages values.
#
# Parameters understood:
#
#   config   (required)
#   autoconf (optional - used by munin-config)
#
# $Log$
# Revision 0.2  2012/11/23 21:20:00  andersevenrud@gmail.com
#               Configuration added
# Revision 0.1  2012/11/22 15:20:00  andersevenrud@gmail.com
#               Initial version
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

VOLTAGE_DESIGN="10800"
VOLTAGE_ULIMIT="12000"
VOLTAGE_LLIMIT="10000"
VOLTAGE_WARNING="10550"
VOLTAGE_CRITICAL="10400"

if [ "$1" = "autoconf" ]; then
  if [ -r /proc/acpi/battery/BAT* ]; then
    echo yes
    exit 0
  else
    echo no
    exit 0
  fi
fi

if [ "$1" = "config" ]; then
  echo 'graph_title Battery Voltage'
  echo "graph_args -u $VOLTAGE_ULIMIT -l $VOLTAGE_LLIMIT"
  echo 'graph_vlabel mV'
  echo 'graph_category ACPI'
  echo 'graph_info This graph shows battery voltage'

  for TYPE in `ls /proc/acpi/battery`; do
    VALUE=`cat /proc/acpi/battery/$TYPE/state | grep voltage | awk '{print $3}'`

    echo  "voltage_$TYPE.warning :$VOLTAGE_WARNING"
    echo  "voltage_$TYPE.critical :$VOLTAGE_CRITICAL"
    echo  "voltage_$TYPE.label $TYPE"
    echo  "voltage_$TYPE.value $VALUE"
  done

  exit 0
fi
