#!/bin/sh
#
# Script to monitor ACPI battery voltages values.
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# $Log$
# Revision 0.1  2012/11/22 15:20:00  andersevenrud@gmail.com
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
  if [ -r /proc/acpi/battery/BAT* ]; then
    echo yes
    exit 0
  else
    echo no
    exit 0
  fi
fi

clean_name() {
    echo $1 $7 $2 | sed 's/[\/.-]/_/g'| awk "{ 
	if (\$3 == \"tmpfs\")
		n=\$1\$2
	else
		n=\$1
	print n
	}"
}

if [ "$1" = "config" ]; then
  echo 'graph_title Battery Voltage (in mV)'
  echo 'graph_args -u 20000 -l 0'
  echo 'graph_vlabel mV'
  echo 'graph_category ACPI'
  echo 'graph_info This graph shows battery voltage'

  for TYPE in `ls /proc/acpi/battery`; do
    VALUE=`cat /proc/acpi/battery/$TYPE/state | grep voltage | awk '{print $3}'`

    name=`clean_name $TYPE`
    echo  "voltage_$name.warning 10800:"
    echo  "voltage_$name.critical 500:"
    echo  "voltage_$name.label $TYPE"
    echo  "voltage_$name.value $VALUE"
  done

  exit 0
fi
