#!/bin/sh
#
# Script to monitor ibm_acpi fan values on thinkpads.
#
# Parameters understood:
#
#   config   (required)
#   autoconf (optional - used by munin-config)
#
# $Log$
# Revision 0.2  2012/11/23 21:20:00  andersevenrud@gmail.com
#               Support for multiple fans
# Revision 0.1  2012/11/22 15:20:00  andersevenrud@gmail.com
#               Initial version
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
  if [ -r /sys/devices/platform/thinkpad_hwmon/fan*_input ]; then
    echo yes
    exit 0
  else
    echo no
    exit 0
  fi
fi

if [ "$1" = "config" ]; then
  echo 'graph_title ibm_acpi fan speed'
  echo 'graph_args -u 5000 -l 0'
  echo 'graph_vlabel RPM'
  echo 'graph_category ACPI'
  echo 'graph_info This graph shows fan values from the ibm_acpi module on Thinkpads.'

  for TYPE in `ls /sys/devices/platform/thinkpad_hwmon/fan*_input`; do
    VALUE=`cat $TYPE`
    NAME=`basename $TYPE | sed -e 's/_input//'`
    NAME="${NAME^}"

    echo  "therm_$NAME.label $NAME"
    echo  "therm_$NAME.value $VALUE"
  done

  TYPE="Fan0"


  exit 0
fi
