#!/bin/sh
#
# Script to monitor ibm_acpi thermal values on thinkpads.
#
# Configuration (ex. Thinkpad R400):
#
# [ibm_acpi]
#   env.labels  HDD,CPU0,CPU1,NA,BAT0,NA,BAT1,NA,Unknown1,Unknown2,Unknown3
#   # Labels with NA are ignored
#
# Parameters understood:
#
#   config   (required)
#   autoconf (optional - used by munin-config)
#
# $Log$
# Revision 0.1  2012/11/24 13:00:00  andersevenrud@gmail.com
#               New version
#
#
# Magic markers (optional - used by munin-config and installation
# scripts):
#
#%# family=auto
#%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
  if [ -r /proc/acpi/ibm/thermal ]; then
    echo yes
    exit 0
  fi

  echo no
  exit 0
fi

if [ "$1" = "config" ]; then
  echo 'graph_title ibm_acpi thermal (in °C)'
  echo 'graph_args -u 120 -l -20'
  echo 'graph_label °C'
  echo 'graph_category ACPI'
  echo 'graph_info This graph shows thermal values from the ibm_acpi module on Thinkpads.'

  LABEL_ARRAY=(`echo $labels | tr "," "\n"`)
  i=0
  for value in `cat /proc/acpi/ibm/thermal |  awk -F: '{print $2}' | tr -d '\t'`; do
    name="${LABEL_ARRAY[$i]}"
    if [[ "$name" != "NA" && -n $name ]]; then
      echo "therm_$name.label $name"
    fi

    i=$i+1
  done

  exit 0
fi

LABEL_ARRAY=(`echo $labels | tr "," "\n"`)
i=0
for value in `cat /proc/acpi/ibm/thermal |  awk -F: '{print $2}' | tr -d '\t'`; do
  name="${LABEL_ARRAY[$i]}"
  if [[ "$name" != "NA" && -n $name ]]; then
    echo "therm_$name.value $value"
  fi

  i=$i+1
done

exit 0
